apiVersion: v1
kind: Pod
metadata:
    labels:
      app: jenkins-slave
    name: kael-k8s-bio-computer
spec:
  volumes:
  - name: work
    nfs:
      server: 192.168.2.200
      path: /local/work

  containers:
  - name: kael-k8s-bio-computer
    image: kaelzhan/bio-computer:latest
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /opt/work
      name: work
    resources:
      limits:
        memory: "8Gi"
        cpu: "8"
      requests:
        memory: "4Gi"
        cpu: "4"